services:
  courses:
    container_name: Courses
    build:
      context: .
      dockerfile: ./Courses/Dockerfile
    image: courses:latest
    ports:
      - "5000:80"
  schedule:
    container_name: Schedule
    build:
      context: .
      dockerfile: ./Schedule/Dockerfile
    image: schedule:latest
    ports:
      - "5001:80"
  gateway:
    container_name: Gateway
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    image: gateway:latest
    ports:
      - "80:80"